add top daily hits and artist profil
jsarni/talent_hunter_project pull request #9
Opened 2020-12-12 22:24 UTC by SAI-Aghylas

2020-12-12 22:29 UTC, SAI-Aghylas commented
forgot to edit main

2020-12-13 16:28 UTC, jsarni requested changes

2020-12-13 16:28 UTC, jsarni commented on collect/conf/AppConfig.py
> +EDGE_TARGET_FOLDER = "~/Bureau/Automatisation/spotify"
Vérifie le target ! j'ai l'impression qu'il est pas bon

2020-12-13 20:40 UTC, merzouk13 approved these changes

2020-12-13 20:42 UTC, jsarni approved these changes

2020-12-13 20:42 UTC, merged